from unittest import TestCase

import numpy

from helpers import string_to_array
from p08.p08 import antinodes

demo_input_8 = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""

example_input_8 = """..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
"""


class Test(TestCase):
    def test_example(self):
        map = string_to_array(example_input_8)
        antinode_map = antinodes(map)
        antinode_count = numpy.count_nonzero(antinode_map)
        self.assertEqual(2, antinode_count)

    def test_demo_part_1(self):
        map = string_to_array(demo_input_8)
        antinode_map = antinodes(map)
        antinode_count = numpy.count_nonzero(antinode_map)
        self.assertEqual(14, antinode_count)
